### ISSUE TITLE
脚本运行报错，大佬帮忙看看~

### ISSUE THREAD

**Issue by zhongzeqing** [dclemon/jdtry#6]
![image](https://user-images.githubusercontent.com/43203407/133379684-a6a2280c-1596-4f5a-b318-a84b3ff57b2a.png)
Traceback (most recent call last):
  File "/scripts/jdtry.py", line 338, in <module>
    main()
  File "/scripts/jdtry.py", line 335, in main
    run()
  File "/scripts/jdtry.py", line 322, in run
    get_try()
  File "/scripts/jdtry.py", line 292, in get_try
    while jd.check_login() == False:
  File "/scripts/jdtry.py", line 84, in check_login
    c = json.loads(res.text)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dclemon** [comment]
这个验证登录的接口被废弃了，注释掉或者自己找个其他接口吧
